-- kitting_schema.sql

-- 1. Add product type flags to existing products table
ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS is_standalone boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS is_custom_box boolean DEFAULT false;

-- 2. Create inventory_purchases table to log supply runs
CREATE TABLE public.inventory_purchases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint REFERENCES public.products ON DELETE CASCADE NOT NULL,
  purchase_date timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  boxes_purchased integer NOT NULL CHECK (boxes_purchased > 0),
  items_per_box integer NOT NULL CHECK (items_per_box > 0),
  total_cost numeric(10,2) NOT NULL CHECK (total_cost >= 0),
  unit_cost numeric(10,4) GENERATED ALWAYS AS (total_cost / (boxes_purchased * items_per_box)) STORED,
  total_yield integer GENERATED ALWAYS AS (boxes_purchased * items_per_box) STORED,
  notes text
);

-- Turn on RLS for inventory_purchases
ALTER TABLE public.inventory_purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated full access inventory_purchases" ON public.inventory_purchases FOR ALL USING (true) WITH CHECK (true);

-- 3. Create product_components table for Bills of Materials (BOM)
CREATE TABLE public.product_components (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_product_id bigint REFERENCES public.products ON DELETE CASCADE NOT NULL,
  component_product_id bigint REFERENCES public.products ON DELETE RESTRICT NOT NULL,
  quantity_needed integer NOT NULL CHECK (quantity_needed > 0),
  UNIQUE(parent_product_id, component_product_id)
);

-- Turn on RLS for product_components
ALTER TABLE public.product_components ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read product_components" ON public.product_components FOR SELECT USING (true);
CREATE POLICY "Allow authenticated full access product_components" ON public.product_components FOR ALL USING (true) WITH CHECK (true);
