-- rbac_schema.sql

-- 1. Create profiles table to link to auth.users and store roles
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email text,
  role text DEFAULT 'staff' CHECK (role IN ('admin', 'staff')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Turn on RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Allow public read of profiles (or restrict to authenticated users)
CREATE POLICY "Allow public read profiles" ON public.profiles
  FOR SELECT USING (true);

-- Trigger to automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'staff'); -- defaults to staff, you can manually change to admin
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if it exists just in case
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. Create price_requests table
CREATE TABLE public.price_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint REFERENCES public.products ON DELETE CASCADE NOT NULL,
  requested_by uuid REFERENCES auth.users ON DELETE SET NULL,
  requested_price numeric(10,2) NOT NULL,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Turn on RLS for price_requests
ALTER TABLE public.price_requests ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to see requests
CREATE POLICY "Allow authenticated read price_requests" ON public.price_requests
  FOR SELECT USING (true);

-- Allow authenticated users to insert requests
CREATE POLICY "Allow authenticated insert price_requests" ON public.price_requests
  FOR INSERT WITH CHECK (true);

-- Allow authenticated users to update requests (Admins will verify this in code/RLS ideally)
CREATE POLICY "Allow authenticated update price_requests" ON public.price_requests
  FOR UPDATE USING (true);
