-- Create the products table
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  tagline text,
  description text,
  price numeric(10,2) NOT NULL DEFAULT 0,
  original_price numeric(10,2),
  image text,
  badge text,
  variants jsonb DEFAULT '[]'::jsonb,
  features jsonb DEFAULT '[]'::jsonb,
  is_waitlist boolean DEFAULT false,
  sku text UNIQUE,
  stock integer NOT NULL DEFAULT 0,
  manufacturing_cost numeric(10,2) NOT NULL DEFAULT 0,
  shipping_cost numeric(10,2) NOT NULL DEFAULT 0,
  packaging_cost numeric(10,2) NOT NULL DEFAULT 0
);

-- Set up Row Level Security (RLS)
-- Allow public read access to products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.products
  FOR SELECT USING (true);

-- Allow authenticated users to insert/update/delete products
-- Note: Since we are using an anon key for the frontend admin panel, we are temporarily allowing all inserts/updates for simplicity.
-- In a real production app, you should use Supabase Auth and restrict these policies.
CREATE POLICY "Allow anon insert" ON public.products
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon update" ON public.products
  FOR UPDATE USING (true);

CREATE POLICY "Allow anon delete" ON public.products
  FOR DELETE USING (true);

-- Insert initial mock data
INSERT INTO public.products (id, slug, name, tagline, description, price, original_price, image, badge, variants, features, is_waitlist, sku, stock, manufacturing_cost, shipping_cost, packaging_cost)
VALUES 
(3, 'diva-cup', 'Diva Cup', '12-hour protection, reusable', 'The Diva Cup provides up to 12 hours of reliable, leak-free protection. Made from 100% medical-grade silicone, it''s reusable, eco-friendly, and perfect for your active lifestyle.', 35.00, NULL, '/images/diva-cup.png', 'Eco Pick', '["Model 0", "Model 1", "Model 2"]', '["Medical-grade silicone", "Lasts up to 10 years", "Saves $1,200+"]', false, 'HFM-DIVA-01', 145, 8.50, 3.00, 1.50),
(4, 'first-period-kit', 'First Period Kit', 'Everything you need, beautifully packaged', 'Our First Period Kit is carefully curated to provide comfort and confidence during your first cycle. Includes premium pads, pantyliners, a discreet carry pouch, and a helpful guide.', 45.00, NULL, '/images/first-period-kit.png', 'Coming Soon', '[]', '["Curated premium essentials", "Step-by-step guide", "Discreet carry pouch"]', true, 'HFM-KIT-01', 0, 15.00, 5.00, 4.50);

-- Create the profiles table
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  first_name text,
  last_name text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);
  
CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Create the period_logs table
CREATE TABLE public.period_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  start_date date NOT NULL,
  end_date date,
  symptoms jsonb DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.period_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own period logs" ON public.period_logs
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own period logs" ON public.period_logs
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own period logs" ON public.period_logs
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own period logs" ON public.period_logs
  FOR DELETE USING (auth.uid() = user_id);

-- Create the subscriptions table
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  stripe_subscription_id text UNIQUE NOT NULL,
  status text NOT NULL,
  plan_name text NOT NULL,
  current_period_end timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own subscriptions" ON public.subscriptions
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow webhook insert subscriptions" ON public.subscriptions
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow webhook update subscriptions" ON public.subscriptions
  FOR UPDATE USING (true);

